package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	contentv1 "gqlgen-playground/internal/pb/content/v1"
	"gqlgen-playground/internal/pkg/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.CreateUserPayload, error) {
	r.contentClient.CreateUser(ctx, *contentv1.CreateUserRequest{
		Username: "",
		Name:     "",
		Email:    nil,
		Phone:    nil,
	})
}
