package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"gqlgen-playground/internal/pkg/model"

	"github.com/google/uuid"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// UserByID is the resolver for the userByID field.
func (r *queryResolver) UserByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UserByID - userByID"))
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id uuid.UUID) (*model.Post, error) {
	panic(fmt.Errorf("not implemented: Post - post"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int32, offset *int32) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit *int32, offset *int32) ([]*model.Post, error) {
	panic(fmt.Errorf("not implemented: Posts - posts"))
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID uuid.UUID, limit *int32, offset *int32) ([]*model.Comment, error) {
	panic(fmt.Errorf("not implemented: Comments - comments"))
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, filter *model.UserFilter, limit *int32) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: SearchUsers - searchUsers"))
}

// ExpensiveAggregation is the resolver for the expensiveAggregation field.
func (r *queryResolver) ExpensiveAggregation(ctx context.Context, input model.ExpensiveInput) (*model.AggregationResult, error) {
	panic(fmt.Errorf("not implemented: ExpensiveAggregation - expensiveAggregation"))
}
