// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: content/v1/content.proto

package contentv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Email         *string                `protobuf:"bytes,7,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,8,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_content_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_content_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_content_v1_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Filter:
	//
	//	*GetUserRequest_Id
	//	*GetUserRequest_Username
	Filter        isGetUserRequest_Filter `protobuf_oneof:"Filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_content_v1_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetFilter() isGetUserRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		if x, ok := x.Filter.(*GetUserRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Filter.(*GetUserRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

type isGetUserRequest_Filter interface {
	isGetUserRequest_Filter()
}

type GetUserRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetUserRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

func (*GetUserRequest_Id) isGetUserRequest_Filter() {}

func (*GetUserRequest_Username) isGetUserRequest_Filter() {}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_content_v1_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Filter        *ListUsersRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Page          int64                    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int64                    `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_content_v1_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersRequest) GetFilter() *ListUsersRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListUsersRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPerPage() int64 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_content_v1_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	AuthorId      string                 `protobuf:"bytes,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_content_v1_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{7}
}

func (x *Post) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Post) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Post) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_content_v1_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePostRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_content_v1_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_content_v1_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{10}
}

func (x *GetPostRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_content_v1_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{11}
}

func (x *GetPostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type ListPostsRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Filter        *ListPostsRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Page          int64                    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int64                    `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsRequest) Reset() {
	*x = ListPostsRequest{}
	mi := &file_content_v1_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsRequest) ProtoMessage() {}

func (x *ListPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsRequest.ProtoReflect.Descriptor instead.
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{12}
}

func (x *ListPostsRequest) GetFilter() *ListPostsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListPostsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPostsRequest) GetPerPage() int64 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsResponse) Reset() {
	*x = ListPostsResponse{}
	mi := &file_content_v1_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsResponse) ProtoMessage() {}

func (x *ListPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsResponse.ProtoReflect.Descriptor instead.
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{13}
}

func (x *ListPostsResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ListPostsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	PostId        string                 `protobuf:"bytes,5,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Body          string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_content_v1_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{14}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Comment) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Comment) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Comment) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_content_v1_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{15}
}

func (x *CreateCommentRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CreateCommentRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreateCommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_content_v1_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type ListCommentsRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Filter        *ListCommentsRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Page          int64                       `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int64                       `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_content_v1_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{17}
}

func (x *ListCommentsRequest) GetFilter() *ListCommentsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListCommentsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommentsRequest) GetPerPage() int64 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_content_v1_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{18}
}

func (x *ListCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListUsersRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdsIn         []string               `protobuf:"bytes,1,rep,name=ids_in,json=idsIn,proto3" json:"ids_in,omitempty"`
	UsernamesIn   []string               `protobuf:"bytes,2,rep,name=usernames_in,json=usernamesIn,proto3" json:"usernames_in,omitempty"`
	CreatedAtFrom *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at_from,json=createdAtFrom,proto3,oneof" json:"created_at_from,omitempty"`
	CreatedAtTo   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at_to,json=createdAtTo,proto3,oneof" json:"created_at_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest_Filter) Reset() {
	*x = ListUsersRequest_Filter{}
	mi := &file_content_v1_content_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest_Filter) ProtoMessage() {}

func (x *ListUsersRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListUsersRequest_Filter) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListUsersRequest_Filter) GetIdsIn() []string {
	if x != nil {
		return x.IdsIn
	}
	return nil
}

func (x *ListUsersRequest_Filter) GetUsernamesIn() []string {
	if x != nil {
		return x.UsernamesIn
	}
	return nil
}

func (x *ListUsersRequest_Filter) GetCreatedAtFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtFrom
	}
	return nil
}

func (x *ListUsersRequest_Filter) GetCreatedAtTo() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtTo
	}
	return nil
}

type ListPostsRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdsIn         []string               `protobuf:"bytes,1,rep,name=ids_in,json=idsIn,proto3" json:"ids_in,omitempty"`
	AuthorIdsIn   []string               `protobuf:"bytes,2,rep,name=author_ids_in,json=authorIdsIn,proto3" json:"author_ids_in,omitempty"`
	CreatedAtFrom *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at_from,json=createdAtFrom,proto3,oneof" json:"created_at_from,omitempty"`
	CreatedAtTo   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at_to,json=createdAtTo,proto3,oneof" json:"created_at_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsRequest_Filter) Reset() {
	*x = ListPostsRequest_Filter{}
	mi := &file_content_v1_content_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsRequest_Filter) ProtoMessage() {}

func (x *ListPostsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListPostsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{12, 0}
}

func (x *ListPostsRequest_Filter) GetIdsIn() []string {
	if x != nil {
		return x.IdsIn
	}
	return nil
}

func (x *ListPostsRequest_Filter) GetAuthorIdsIn() []string {
	if x != nil {
		return x.AuthorIdsIn
	}
	return nil
}

func (x *ListPostsRequest_Filter) GetCreatedAtFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtFrom
	}
	return nil
}

func (x *ListPostsRequest_Filter) GetCreatedAtTo() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtTo
	}
	return nil
}

type ListCommentsRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdsIn         []string               `protobuf:"bytes,1,rep,name=ids_in,json=idsIn,proto3" json:"ids_in,omitempty"`
	AuthorIdsIn   []string               `protobuf:"bytes,2,rep,name=author_ids_in,json=authorIdsIn,proto3" json:"author_ids_in,omitempty"`
	PostIdsIn     []string               `protobuf:"bytes,3,rep,name=post_ids_in,json=postIdsIn,proto3" json:"post_ids_in,omitempty"`
	CreatedAtFrom *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at_from,json=createdAtFrom,proto3,oneof" json:"created_at_from,omitempty"`
	CreatedAtTo   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at_to,json=createdAtTo,proto3,oneof" json:"created_at_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest_Filter) Reset() {
	*x = ListCommentsRequest_Filter{}
	mi := &file_content_v1_content_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest_Filter) ProtoMessage() {}

func (x *ListCommentsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{17, 0}
}

func (x *ListCommentsRequest_Filter) GetIdsIn() []string {
	if x != nil {
		return x.IdsIn
	}
	return nil
}

func (x *ListCommentsRequest_Filter) GetAuthorIdsIn() []string {
	if x != nil {
		return x.AuthorIdsIn
	}
	return nil
}

func (x *ListCommentsRequest_Filter) GetPostIdsIn() []string {
	if x != nil {
		return x.PostIdsIn
	}
	return nil
}

func (x *ListCommentsRequest_Filter) GetCreatedAtFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtFrom
	}
	return nil
}

func (x *ListCommentsRequest_Filter) GetCreatedAtTo() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtTo
	}
	return nil
}

var File_content_v1_content_proto protoreflect.FileDescriptor

const file_content_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x18content/v1/content.proto\x12\n" +
	"content.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x19\n" +
	"\x05email\x18\a \x01(\tH\x01R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\b \x01(\tH\x02R\x05phone\x88\x01\x01B\r\n" +
	"\v_deleted_atB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phone\"\x8d\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x01R\x05phone\x88\x01\x01B\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phone\":\n" +
	"\x12CreateUserResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.content.v1.UserR\x04user\"J\n" +
	"\x0eGetUserRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busernameB\b\n" +
	"\x06Filter\"7\n" +
	"\x0fGetUserResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.content.v1.UserR\x04user\"\xf7\x02\n" +
	"\x10ListUsersRequest\x12;\n" +
	"\x06filter\x18\x01 \x01(\v2#.content.v1.ListUsersRequest.FilterR\x06filter\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x03R\aperPage\x1a\xf6\x01\n" +
	"\x06Filter\x12\x15\n" +
	"\x06ids_in\x18\x01 \x03(\tR\x05idsIn\x12!\n" +
	"\fusernames_in\x18\x02 \x03(\tR\vusernamesIn\x12G\n" +
	"\x0fcreated_at_from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\rcreatedAtFrom\x88\x01\x01\x12C\n" +
	"\rcreated_at_to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vcreatedAtTo\x88\x01\x01B\x12\n" +
	"\x10_created_at_fromB\x10\n" +
	"\x0e_created_at_to\"Q\n" +
	"\x11ListUsersResponse\x12&\n" +
	"\x05users\x18\x01 \x03(\v2\x10.content.v1.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa2\x02\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04bodyB\r\n" +
	"\v_deleted_at\"Z\n" +
	"\x11CreatePostRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\":\n" +
	"\x12CreatePostResponse\x12$\n" +
	"\x04post\x18\x01 \x01(\v2\x10.content.v1.PostR\x04post\" \n" +
	"\x0eGetPostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x0fGetPostResponse\x12$\n" +
	"\x04post\x18\x01 \x01(\v2\x10.content.v1.PostR\x04post\"\xf8\x02\n" +
	"\x10ListPostsRequest\x12;\n" +
	"\x06filter\x18\x01 \x01(\v2#.content.v1.ListPostsRequest.FilterR\x06filter\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x03R\aperPage\x1a\xf7\x01\n" +
	"\x06Filter\x12\x15\n" +
	"\x06ids_in\x18\x01 \x03(\tR\x05idsIn\x12\"\n" +
	"\rauthor_ids_in\x18\x02 \x03(\tR\vauthorIdsIn\x12G\n" +
	"\x0fcreated_at_from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\rcreatedAtFrom\x88\x01\x01\x12C\n" +
	"\rcreated_at_to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vcreatedAtTo\x88\x01\x01B\x12\n" +
	"\x10_created_at_fromB\x10\n" +
	"\x0e_created_at_to\"Q\n" +
	"\x11ListPostsResponse\x12&\n" +
	"\x05posts\x18\x01 \x03(\v2\x10.content.v1.PostR\x05posts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa8\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01\x12\x17\n" +
	"\apost_id\x18\x05 \x01(\tR\x06postId\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04bodyB\r\n" +
	"\v_deleted_at\"`\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"F\n" +
	"\x15CreateCommentResponse\x12-\n" +
	"\acomment\x18\x01 \x01(\v2\x13.content.v1.CommentR\acomment\"\x9e\x03\n" +
	"\x13ListCommentsRequest\x12>\n" +
	"\x06filter\x18\x01 \x01(\v2&.content.v1.ListCommentsRequest.FilterR\x06filter\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x03R\aperPage\x1a\x97\x02\n" +
	"\x06Filter\x12\x15\n" +
	"\x06ids_in\x18\x01 \x03(\tR\x05idsIn\x12\"\n" +
	"\rauthor_ids_in\x18\x02 \x03(\tR\vauthorIdsIn\x12\x1e\n" +
	"\vpost_ids_in\x18\x03 \x03(\tR\tpostIdsIn\x12G\n" +
	"\x0fcreated_at_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\rcreatedAtFrom\x88\x01\x01\x12C\n" +
	"\rcreated_at_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vcreatedAtTo\x88\x01\x01B\x12\n" +
	"\x10_created_at_fromB\x10\n" +
	"\x0e_created_at_to\"]\n" +
	"\x14ListCommentsResponse\x12/\n" +
	"\bcomments\x18\x01 \x03(\v2\x13.content.v1.CommentR\bcomments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xef\x04\n" +
	"\x0eContentService\x12K\n" +
	"\n" +
	"CreateUser\x12\x1d.content.v1.CreateUserRequest\x1a\x1e.content.v1.CreateUserResponse\x12B\n" +
	"\aGetUser\x12\x1a.content.v1.GetUserRequest\x1a\x1b.content.v1.GetUserResponse\x12H\n" +
	"\tListUsers\x12\x1c.content.v1.ListUsersRequest\x1a\x1d.content.v1.ListUsersResponse\x12K\n" +
	"\n" +
	"CreatePost\x12\x1d.content.v1.CreatePostRequest\x1a\x1e.content.v1.CreatePostResponse\x12B\n" +
	"\aGetPost\x12\x1a.content.v1.GetPostRequest\x1a\x1b.content.v1.GetPostResponse\x12H\n" +
	"\tListPosts\x12\x1c.content.v1.ListPostsRequest\x1a\x1d.content.v1.ListPostsResponse\x12T\n" +
	"\rCreateComment\x12 .content.v1.CreateCommentRequest\x1a!.content.v1.CreateCommentResponse\x12Q\n" +
	"\fListComments\x12\x1f.content.v1.ListCommentsRequest\x1a .content.v1.ListCommentsResponseB4Z2gqlgen-playground/internal/pb/content/v1;contentv1b\x06proto3"

var (
	file_content_v1_content_proto_rawDescOnce sync.Once
	file_content_v1_content_proto_rawDescData []byte
)

func file_content_v1_content_proto_rawDescGZIP() []byte {
	file_content_v1_content_proto_rawDescOnce.Do(func() {
		file_content_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_v1_content_proto_rawDesc), len(file_content_v1_content_proto_rawDesc)))
	})
	return file_content_v1_content_proto_rawDescData
}

var file_content_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_content_v1_content_proto_goTypes = []any{
	(*User)(nil),                       // 0: content.v1.User
	(*CreateUserRequest)(nil),          // 1: content.v1.CreateUserRequest
	(*CreateUserResponse)(nil),         // 2: content.v1.CreateUserResponse
	(*GetUserRequest)(nil),             // 3: content.v1.GetUserRequest
	(*GetUserResponse)(nil),            // 4: content.v1.GetUserResponse
	(*ListUsersRequest)(nil),           // 5: content.v1.ListUsersRequest
	(*ListUsersResponse)(nil),          // 6: content.v1.ListUsersResponse
	(*Post)(nil),                       // 7: content.v1.Post
	(*CreatePostRequest)(nil),          // 8: content.v1.CreatePostRequest
	(*CreatePostResponse)(nil),         // 9: content.v1.CreatePostResponse
	(*GetPostRequest)(nil),             // 10: content.v1.GetPostRequest
	(*GetPostResponse)(nil),            // 11: content.v1.GetPostResponse
	(*ListPostsRequest)(nil),           // 12: content.v1.ListPostsRequest
	(*ListPostsResponse)(nil),          // 13: content.v1.ListPostsResponse
	(*Comment)(nil),                    // 14: content.v1.Comment
	(*CreateCommentRequest)(nil),       // 15: content.v1.CreateCommentRequest
	(*CreateCommentResponse)(nil),      // 16: content.v1.CreateCommentResponse
	(*ListCommentsRequest)(nil),        // 17: content.v1.ListCommentsRequest
	(*ListCommentsResponse)(nil),       // 18: content.v1.ListCommentsResponse
	(*ListUsersRequest_Filter)(nil),    // 19: content.v1.ListUsersRequest.Filter
	(*ListPostsRequest_Filter)(nil),    // 20: content.v1.ListPostsRequest.Filter
	(*ListCommentsRequest_Filter)(nil), // 21: content.v1.ListCommentsRequest.Filter
	(*timestamppb.Timestamp)(nil),      // 22: google.protobuf.Timestamp
}
var file_content_v1_content_proto_depIdxs = []int32{
	22, // 0: content.v1.User.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: content.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	22, // 2: content.v1.User.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: content.v1.CreateUserResponse.user:type_name -> content.v1.User
	0,  // 4: content.v1.GetUserResponse.user:type_name -> content.v1.User
	19, // 5: content.v1.ListUsersRequest.filter:type_name -> content.v1.ListUsersRequest.Filter
	0,  // 6: content.v1.ListUsersResponse.users:type_name -> content.v1.User
	22, // 7: content.v1.Post.created_at:type_name -> google.protobuf.Timestamp
	22, // 8: content.v1.Post.updated_at:type_name -> google.protobuf.Timestamp
	22, // 9: content.v1.Post.deleted_at:type_name -> google.protobuf.Timestamp
	7,  // 10: content.v1.CreatePostResponse.post:type_name -> content.v1.Post
	7,  // 11: content.v1.GetPostResponse.post:type_name -> content.v1.Post
	20, // 12: content.v1.ListPostsRequest.filter:type_name -> content.v1.ListPostsRequest.Filter
	7,  // 13: content.v1.ListPostsResponse.posts:type_name -> content.v1.Post
	22, // 14: content.v1.Comment.created_at:type_name -> google.protobuf.Timestamp
	22, // 15: content.v1.Comment.updated_at:type_name -> google.protobuf.Timestamp
	22, // 16: content.v1.Comment.deleted_at:type_name -> google.protobuf.Timestamp
	14, // 17: content.v1.CreateCommentResponse.comment:type_name -> content.v1.Comment
	21, // 18: content.v1.ListCommentsRequest.filter:type_name -> content.v1.ListCommentsRequest.Filter
	14, // 19: content.v1.ListCommentsResponse.comments:type_name -> content.v1.Comment
	22, // 20: content.v1.ListUsersRequest.Filter.created_at_from:type_name -> google.protobuf.Timestamp
	22, // 21: content.v1.ListUsersRequest.Filter.created_at_to:type_name -> google.protobuf.Timestamp
	22, // 22: content.v1.ListPostsRequest.Filter.created_at_from:type_name -> google.protobuf.Timestamp
	22, // 23: content.v1.ListPostsRequest.Filter.created_at_to:type_name -> google.protobuf.Timestamp
	22, // 24: content.v1.ListCommentsRequest.Filter.created_at_from:type_name -> google.protobuf.Timestamp
	22, // 25: content.v1.ListCommentsRequest.Filter.created_at_to:type_name -> google.protobuf.Timestamp
	1,  // 26: content.v1.ContentService.CreateUser:input_type -> content.v1.CreateUserRequest
	3,  // 27: content.v1.ContentService.GetUser:input_type -> content.v1.GetUserRequest
	5,  // 28: content.v1.ContentService.ListUsers:input_type -> content.v1.ListUsersRequest
	8,  // 29: content.v1.ContentService.CreatePost:input_type -> content.v1.CreatePostRequest
	10, // 30: content.v1.ContentService.GetPost:input_type -> content.v1.GetPostRequest
	12, // 31: content.v1.ContentService.ListPosts:input_type -> content.v1.ListPostsRequest
	15, // 32: content.v1.ContentService.CreateComment:input_type -> content.v1.CreateCommentRequest
	17, // 33: content.v1.ContentService.ListComments:input_type -> content.v1.ListCommentsRequest
	2,  // 34: content.v1.ContentService.CreateUser:output_type -> content.v1.CreateUserResponse
	4,  // 35: content.v1.ContentService.GetUser:output_type -> content.v1.GetUserResponse
	6,  // 36: content.v1.ContentService.ListUsers:output_type -> content.v1.ListUsersResponse
	9,  // 37: content.v1.ContentService.CreatePost:output_type -> content.v1.CreatePostResponse
	11, // 38: content.v1.ContentService.GetPost:output_type -> content.v1.GetPostResponse
	13, // 39: content.v1.ContentService.ListPosts:output_type -> content.v1.ListPostsResponse
	16, // 40: content.v1.ContentService.CreateComment:output_type -> content.v1.CreateCommentResponse
	18, // 41: content.v1.ContentService.ListComments:output_type -> content.v1.ListCommentsResponse
	34, // [34:42] is the sub-list for method output_type
	26, // [26:34] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_content_v1_content_proto_init() }
func file_content_v1_content_proto_init() {
	if File_content_v1_content_proto != nil {
		return
	}
	file_content_v1_content_proto_msgTypes[0].OneofWrappers = []any{}
	file_content_v1_content_proto_msgTypes[1].OneofWrappers = []any{}
	file_content_v1_content_proto_msgTypes[3].OneofWrappers = []any{
		(*GetUserRequest_Id)(nil),
		(*GetUserRequest_Username)(nil),
	}
	file_content_v1_content_proto_msgTypes[7].OneofWrappers = []any{}
	file_content_v1_content_proto_msgTypes[14].OneofWrappers = []any{}
	file_content_v1_content_proto_msgTypes[19].OneofWrappers = []any{}
	file_content_v1_content_proto_msgTypes[20].OneofWrappers = []any{}
	file_content_v1_content_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_v1_content_proto_rawDesc), len(file_content_v1_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_content_v1_content_proto_goTypes,
		DependencyIndexes: file_content_v1_content_proto_depIdxs,
		MessageInfos:      file_content_v1_content_proto_msgTypes,
	}.Build()
	File_content_v1_content_proto = out.File
	file_content_v1_content_proto_goTypes = nil
	file_content_v1_content_proto_depIdxs = nil
}
